### PR TITLE
[JENKINS-49573]  core-1.651.3 + matrix-project-1.7

### PR DESCRIPTION
**Pull request by ikedam**
Testing additional changes for #23.
Use matrix-project-1.4.1 which is bundled with Jenkins 1.625.3.

### CODE REVIEW

**Comment by ikedam** [comment]
It doesn't look hit UpperBound problem even with `mvn test -Djenkins.version=2.102 -Djava.level=8`

**Comment by ikedam** [comment]
Tests fail for
```
   0.690 [id=1146]	WARNING	hudson.model.ParametersAction#filter: Skipped parameter `combinations` as it is undefined on `test0/axis1=value2`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach or `-Dhudson.model.ParametersAction.keepUndefinedParameters=false` to no longer show this message.
```

This is SECURITY-170: https://jenkins.io/blog/2016/05/11/security-update/
Matrix-project >= 1.7 is required to fix this issue.

**Comment by ikedam** [comment]
There look failures even using matrix-project 1.7.
Need more investigation.

**Comment by jglick** [comment]
I will check any test failures in #25, but why do you think you need to backdate the `matrix-project` dependency? What is bundled in obsolete Jenkins versions is not really relevant.

**Comment by ikedam** [comment]
I want (wanted) to clarify what requires the latest matrix-project plugin.
I can use the latest (or 1.7 in this case) one if there's a reason.

**Comment by ikedam** [comment]
I saw that test failures reproduces even with matrix-project-1.12 when run with Jenkins 2.102 (that means, #23).
It should be caused for rebuild-plugin as pointed in https://github.com/jenkinsci/matrix-combinations-plugin/pull/25#issuecomment-368163654.

**Pull request merged**
